[build]
  command = "npm run build"
  publish = "netlify-dist"

[[redirects]]
  from = "/"
  to = "/en-US/"
  status = 301
  force = true

[[redirects]]
  from = "/en-US/*"
  to = "/en-US/index.html"
  status = 200

[[redirects]]
  from = "/ar-AE/*"
  to = "/ar-AE/index.html"
  status = 200
