[build]
  # Single command that builds everything needed
  command = "ng build --localize"
  publish = "dist/multi-language-test/browser"  # Directly use Angular's output

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/ar/*"
  to = "/ar/index.html"
  status = 200
