[build]
  command = "ng build --configuration production"
  publish = "dist/browser/en"

[[redirects]]
  from = "/ar/*"
  to = "/ar/index.html"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
