[build]
  publish = "netlify-dist"
  command = "npm run build"

  
[[redirects]]
  from = "/ar/*"
  to = "/ar/index.html"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200