[build]
  command = "npm run build"
  publish = "netlify-dist"

[plugins]
  # Disable automatic plugin detection
  package = ""

[[redirects]]
  from = "/"
  to = "/en/"
  status = 301
  force = true

[[redirects]]
  from = "/en/*"
  to = "/en/index.html"
  status = 200

[[redirects]]
  from = "/ar-AE/*"
  to = "/ar-AE/index.html"
  status = 200
